name: 'publish'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi
      - run: |
          cargo install wasm-tools
      - run: |
          node build.js
      - uses: actions/upload-artifact@v3
        with:
          name: index
          path: index.json
      - uses: actions/upload-artifact@v3
        with:
          name: built
          path: built/
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: index
          path: _index.json
      - uses: actions/download-artifact@v3
        with:
          name: built
          path: _plugins

      - run: |
          mv _index.json index.json
          mkdir -p plugins
          mv cp -r _plugins/* plugins/

          rm _index.json
          rm -rf _plugins
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
      